sudo: required
services:
  - docker  # tell the travis that we need a copy of docker to ready to go

before-install:
  - docker build -t kajal1501/docker-react -f Dockerfile.dev . #convention of image is what we used, you can use any image name

script:
  - docker run -e CI=true kajal1501/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "your-aws-region"
  app: "name-of-aws-eb-app"
  env: "env-name-of-eb"
  bucket_name: "s3-bucket-name-generated-by-eb"
  bucket_path: "bucket_path"   #it could be same as 'app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY   #this variable will be replaced by travis ci variables key value
  secret_access_key: "$AWS_SECRET_KEY"